version: '2'
config:
    slack_notify: true
    slack_channel: astra_ci
environment:
    BUILD_IMAGE: 'maven:3.6-jdk-11'
credentials:
    text:
        - GITHUB_TOKEN_READ_ORG_A
jobs:
    build:
        docker:
            - image:
                  name: '{{ .env.BUILD_IMAGE }}'
        steps:
            - restore_cache:
              key: astra-explorer
            - save_cache:
              key: astra-explorer
              paths:
                  - astra-explorer
    build_docker:
        steps:
            - build_image:
              build_args: '--build-arg GITHUB_TOKEN=${GITHUB_TOKEN_READ_ORG_A}'
    publish_docker:
        steps:
            - push_image
    deploy_dev:
        steps:
            - deploy_dev:
                  cluster: dev
                  namespace: astra
                  workload: explorer
                  argocd_pipeline: generic-v2
                  deployment_config: dev
    deploy_prod:
        steps:
            - deploy_production:
                  cluster: k8s-astra-prod
                  namespace: default
                  workload: explorer
                  argocd_pipeline: generic-v2
                  deployment_config: prod
workflows:
    jenkins_pipeline:
        jobs:
            - build_docker:
                  filters:
                      branches:
                          only:
                              - dev
                              - main
            - publish_docker:
                  requires:
                      - build_docker
                  filters:
                      branches:
                          only:
                              - dev
                              - main
            - deploy_dev:
                  requires:
                      - publish_docker
                  filters:
                      branches:
                          only:
                              - dev
            - deploy_prod:
                  requires:
                      - publish_docker
                  filters:
                      branches:
                          only:
                              - main
deployment_config:
    dev:
        ingress:
            hosts:
                - host: explorer.dev.tiki.services
                  paths:
                      - path: /
                        port: '3000'
        envFrom:
            - secretRef:
                  name: env-explorer-fe
                  optional: false
        replicaCount: 1
    prod:
        ingress:
            hosts:
                - host: explorer.tiki.services
                  paths:
                      - path: /
                        port: '3000'
        envFrom:
            - secretRef:
                  name: env-explorer-fe
                  optional: false
        replicaCount: 1
