name: Production deployment
on:
  push:
    branches: ['main']

 
jobs:
  build-and-deploy:
     uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment-advanced.yml@main
     secrets:
       secretBuildArgs: |
         SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
         GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
     with:
       ingressEnabled: "yes"
       ingressHost: "explorer.prod.astranet.services"
       replicas: "2"
       servicePort: "3000"
       buildArgs: |-
        NEXT_PUBLIC_COSMOS_API=https://chainindexing.astranaut.io
        NEXT_PUBLIC_EVM_API=https://blockscout.astranaut.io
        NEXT_PUBLIC_URL=https://explorer.astranaut.io
        NEXT_PUBLIC_CHAIN_ID=11110
        NEXT_PUBLIC_TITLE=Astra Explorer
        NEXT_PUBLIC_GA_MEASUREMENT_ID=G-1KW22EJBY5
        NEXT_PUBLIC_SENTRY_DSN=https://e5a0c44ff6ed4b9b967c490d4587a1b9@sentry.astranet.live/2
        NEXT_PUBLIC_ENV=mainnet
